version: "3.7"
services: 
  label-hub-ui:
    build: .
    container_name: label-hub-ui
    env_file:
      - .env
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - label-hub-ui-node_modules:/app/node_modules
volumes:
  label-hub-ui-node_modules:


